{extends file='../templates/layout.tpl'}

{block name=title}
	Historique du CA
{/block}

{block name=body}
          <h1 class="page-header">HISTORIQUE DES PARIS</h1>
<h4 class="sub-header">EN CHIFFRE D'AFFAIRES</h4>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead style="background-color: green; color: white;">
                <tr>
                  <th>NOM DE L’INDICATEUR</th>
                  <th>2014</th>
                  <th>2015</th>
                  <th>2016</th>
                  <th>2017</th>
				  <th>2018</td>
					<th>2019</td>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>JANVIER</td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
					<td>5</td>
					<td>6</td>
                </tr>
                <tr>
                  <td>FEVRIER</td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
					<td>5</td>
					<td>6</td>
                </tr>
                <tr>
                  <td>MARS</td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
					<td>5</td>
					<td>6</td>
                </tr>
                <tr>
                  <td>AVRIL</td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
					<td>5</td>
					<td>6</td>
                </tr>
                <tr>
                  <td>MAI</td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
					<td>5</td>
					<td>6</td>
                </tr>
                <tr>
                  <td>JUIN</td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
					<td>5</td>
					<td>6</td>
                </tr>
                <tr>
                  <td>JUILLET</td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
					<td>5</td>
					<td>6</td>
                </tr>
                <tr>
                  <td>AOUT</td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
					<td>5</td>
					<td>6</td>
                </tr>
                <tr>
                  <td>SEPTEMBRE</td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
					<td>5</td>
					<td>6</td>
                </tr>
                <tr>
                  <td>OCTOBRE</td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
					<td>5</td>
					<td>6</td>
                </tr>
                <tr>
                  <td>NOVEMBRE</td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
					<td>5</td>
					<td>6</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
					<td>5</td>
					<td>6</td>
                </tr>
                <tr>
                  <td>DECEMBRE</td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
					<td>5</td>
					<td>6</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
{/block}
